<?php

namespace Database\Seeders;

use App\Models\FacilityCost;
use Illuminate\Database\Seeder;

class FacilityCostSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'classroom_name' => 'CM 201',
                'supply_cost' => 6.00,
                'electricity_cost' => 12.50,
                'water_cost' => 6.25,
                'classroom_space' => 568.00,
                'daily_cost_1' => 0.21,
                'daily_cost_2' => 0.26,
                'daily_cost_3' => 0.31,
                'weekly_cost_1' => 0.86,
                'weekly_cost_2' => 1.03,
                'weekly_cost_3' => 1.03,
                'monthly_cost_1' => 2.74,
                'monthly_cost_2' => 3.29,
                'monthly_cost_3' => 3.29,
            ],
            [
                'classroom_name' => 'CM 202',
                'supply_cost' => 6.00,
                'electricity_cost' => 12.50,
                'water_cost' => 6.25,
                'classroom_space' => 564.00,
                'daily_cost_1' => 0.21,
                'daily_cost_2' => 0.26,
                'daily_cost_3' => 0.31,
                'weekly_cost_1' => 0.86,
                'weekly_cost_2' => 1.03,
                'weekly_cost_3' => 1.03,
                'monthly_cost_1' => 2.74,
                'monthly_cost_2' => 3.29,
                'monthly_cost_3' => 3.29,
            ],
            [
                'classroom_name' => 'Cancha CM',
                'supply_cost' => 120.00,
                'electricity_cost' => 250.00,
                'water_cost' => 125.00,
                'classroom_space' => 12082.00,
                'daily_cost_1' => 0.21,
                'daily_cost_2' => 0.26,
                'daily_cost_3' => 0.31,
                'weekly_cost_1' => 0.86,
                'weekly_cost_2' => 1.03,
                'weekly_cost_3' => 1.03,
                'monthly_cost_1' => 2.74,
                'monthly_cost_2' => 3.29,
                'monthly_cost_3' => 3.29,
            ],
            [
                'classroom_name' => 'Lateral 1',
                'supply_cost' => 30.00,
                'electricity_cost' => 75.00,
                'water_cost' => 37.50,
                'classroom_space' => 4706.00,
                'daily_cost_1' => 0.21,
                'daily_cost_2' => 0.26,
                'daily_cost_3' => 0.31,
                'weekly_cost_1' => 0.86,
                'weekly_cost_2' => 1.03,
                'weekly_cost_3' => 1.03,
                'monthly_cost_1' => 2.74,
                'monthly_cost_2' => 3.29,
                'monthly_cost_3' => 3.29,
            ],
            [
                'classroom_name' => 'Lateral 2',
                'supply_cost' => 30.00,
                'electricity_cost' => 75.00,
                'water_cost' => 37.50,
                'classroom_space' => 4706.00,
                'daily_cost_1' => 0.21,
                'daily_cost_2' => 0.26,
                'daily_cost_3' => 0.31,
                'weekly_cost_1' => 0.86,
                'weekly_cost_2' => 1.03,
                'weekly_cost_3' => 1.03,
                'monthly_cost_1' => 2.74,
                'monthly_cost_2' => 3.29,
                'monthly_cost_3' => 3.29,
            ],
            [
                'classroom_name' => 'CM 203',
                'supply_cost' => 6.00,
                'electricity_cost' => 12.50,
                'water_cost' => 6.25,
                'classroom_space' => 564.00,
                'daily_cost_1' => 0.21,
                'daily_cost_2' => 0.26,
                'daily_cost_3' => 0.31,
                'weekly_cost_1' => 0.86,
                'weekly_cost_2' => 1.03,
                'weekly_cost_3' => 1.03,
                'monthly_cost_1' => 2.74,
                'monthly_cost_2' => 3.29,
                'monthly_cost_3' => 3.29,
            ],
            [
                'classroom_name' => 'CM 204',
                'supply_cost' => 6.00,
                'electricity_cost' => 12.50,
                'water_cost' => 6.25,
                'classroom_space' => 568.00,
                'daily_cost_1' => 0.21,
                'daily_cost_2' => 0.26,
                'daily_cost_3' => 0.31,
                'weekly_cost_1' => 0.86,
                'weekly_cost_2' => 1.03,
                'weekly_cost_3' => 1.03,
                'monthly_cost_1' => 2.74,
                'monthly_cost_2' => 3.29,
                'monthly_cost_3' => 3.29,
            ],
            [
                'classroom_name' => 'CM 210',
                'supply_cost' => 12.00,
                'electricity_cost' => 25.00,
                'water_cost' => 12.50,
                'classroom_space' => 820.00,
                'daily_cost_1' => 0.21,
                'daily_cost_2' => 0.26,
                'daily_cost_3' => 0.31,
                'weekly_cost_1' => 0.86,
                'weekly_cost_2' => 1.03,
                'weekly_cost_3' => 1.03,
                'monthly_cost_1' => 2.74,
                'monthly_cost_2' => 3.29,
                'monthly_cost_3' => 3.29,
            ],
        ];

        foreach ($rows as $row) {
            FacilityCost::updateOrCreate(
                ['classroom_name' => $row['classroom_name']],
                $row
            );
        }
    }
}