<?php

namespace Database\Seeders;

use App\Models\FacilityCost;
use Illuminate\Database\Seeder;

class FacilityCostSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'classroom_name' => 'CM 201',
                'supply_cost' => 0.32,
                'electricity_cost' => 0.38,
                'water_cost' => 0.08,
                'classroom_space' => 568.00,
                'daily_cost_1' => 0.25,
                'daily_cost_2' => 0.31,
                'daily_cost_3' => 0.37,
                'weekly_cost_1' => 1.03,
                'weekly_cost_2' => 1.23,
                'weekly_cost_3' => 0.37,
                'monthly_cost_1' => 3.27,
                'monthly_cost_2' => 3.93,
                'monthly_cost_3' => 0.37,
            ],
            [
                'classroom_name' => 'CM 202',
                'supply_cost' => 0.32,
                'electricity_cost' => 0.38,
                'water_cost' => 0.08,
                'classroom_space' => 564.00,
                'daily_cost_1' => 0.25,
                'daily_cost_2' => 0.31,
                'daily_cost_3' => 0.37,
                'weekly_cost_1' => 1.03,
                'weekly_cost_2' => 1.23,
                'weekly_cost_3' => 0.37,
                'monthly_cost_1' => 3.27,
                'monthly_cost_2' => 3.93,
                'monthly_cost_3' => 0.37,
            ],
            [
                'classroom_name' => 'Cancha CM',
                'supply_cost' => 6.88,
                'electricity_cost' => 8.13,
                'water_cost' => 1.79,
                'classroom_space' => 12082.00,
                'daily_cost_1' => 0.25,
                'daily_cost_2' => 0.31,
                'daily_cost_3' => 0.37,
                'weekly_cost_1' => 1.03,
                'weekly_cost_2' => 1.23,
                'weekly_cost_3' => 0.37,
                'monthly_cost_1' => 3.27,
                'monthly_cost_2' => 3.93,
                'monthly_cost_3' => 0.37,
            ],
            [
                'classroom_name' => 'Lateral 1 Área Judo',
                'supply_cost' => 2.68,
                'electricity_cost' => 3.17,
                'water_cost' => 0.70,
                'classroom_space' => 4706.00,
                'daily_cost_1' => 0.25,
                'daily_cost_2' => 0.31,
                'daily_cost_3' => 0.37,
                'weekly_cost_1' => 1.03,
                'weekly_cost_2' => 1.23,
                'weekly_cost_3' => 0.37,
                'monthly_cost_1' => 3.27,
                'monthly_cost_2' => 3.93,
                'monthly_cost_3' => 0.37,
            ],
            [
                'classroom_name' => 'Lateral 2 Deportes Recreativos',
                'supply_cost' => 2.68,
                'electricity_cost' => 3.17,
                'water_cost' => 0.70,
                'classroom_space' => 4706.00,
                'daily_cost_1' => 0.25,
                'daily_cost_2' => 0.31,
                'daily_cost_3' => 0.37,
                'weekly_cost_1' => 1.03,
                'weekly_cost_2' => 1.23,
                'weekly_cost_3' => 0.37,
                'monthly_cost_1' => 3.27,
                'monthly_cost_2' => 3.93,
                'monthly_cost_3' => 0.37,
            ],
            [
                'classroom_name' => 'CM 203',
                'supply_cost' => 0.32,
                'electricity_cost' => 0.38,
                'water_cost' => 0.08,
                'classroom_space' => 564.00,
                'daily_cost_1' => 0.25,
                'daily_cost_2' => 0.31,
                'daily_cost_3' => 0.37,
                'weekly_cost_1' => 1.03,
                'weekly_cost_2' => 1.23,
                'weekly_cost_3' => 0.37,
                'monthly_cost_1' => 3.27,
                'monthly_cost_2' => 3.93,
                'monthly_cost_3' => 0.37,
            ],
            [
                'classroom_name' => 'CM 204',
                'supply_cost' => 0.32,
                'electricity_cost' => 0.38,
                'water_cost' => 0.08,
                'classroom_space' => 568.00,
                'daily_cost_1' => 0.25,
                'daily_cost_2' => 0.31,
                'daily_cost_3' => 0.37,
                'weekly_cost_1' => 1.03,
                'weekly_cost_2' => 1.23,
                'weekly_cost_3' => 0.37,
                'monthly_cost_1' => 3.27,
                'monthly_cost_2' => 3.93,
                'monthly_cost_3' => 0.37,
            ],
            [
                'classroom_name' => 'CM 210',
                'supply_cost' => 0.47,
                'electricity_cost' => 0.55,
                'water_cost' => 0.12,
                'classroom_space' => 820.00,
                'daily_cost_1' => 0.25,
                'daily_cost_2' => 0.31,
                'daily_cost_3' => 0.37,
                'weekly_cost_1' => 1.03,
                'weekly_cost_2' => 1.23,
                'weekly_cost_3' => 0.37,
                'monthly_cost_1' => 3.27,
                'monthly_cost_2' => 3.93,
                'monthly_cost_3' => 0.37,
            ],
        ];

        foreach ($rows as $row) {
            FacilityCost::updateOrCreate(
                ['classroom_name' => $row['classroom_name']],
                $row
            );
        }
    }
}
